# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
    nodejs: latest
  jobs:
    create_environment:
      - mise install uv@latest
      - mise use -g uv@latest
    build:
      html:
        - uvx hatch run docs:build
        - mv docs/_build $READTHEDOCS_OUTPUT
